name: Build and Test Docker Image

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t sjuprojekt .

      - name: Run test script inside container
        run: |
          docker run --rm sjuprojekt python /home/vscode/workspace/test.py
