name: Deploy MARP presentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload GitHub Pages content
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
